default_install_hook_types: [ pre-push ]
default_stages: [ pre-push ]

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check ./
        language: system
        pass_filenames: false
        always_run: true

      - id: mypy-src
        name: mypy src
        entry: uv run mypy src
        language: system
        pass_filenames: false
        always_run: true

      - id: unittest
        name: python unittest
        entry: uv run python -m unittest
        language: system
        pass_filenames: false
        always_run: true
